
version: '3'

services:

  agentspirs1:
    image: agentspirs:1.0.0
    container_name: agentspirs1
    cap_add:
      - ALL
    networks:
      - network1
      - custom_bridge
    stdin_open: true
    tty: true

  agentspirs2:
    image: agentspirs:1.0.0
    container_name: agentspirs2
    cap_add:
      - ALL
    networks:
      - network2
      - custom_bridge
    stdin_open: true
    tty: true

networks:

  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/24

  network2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.1.0/24

  custom_bridge:
    external: true
